name: Deployment
on:
  push:
    branches:
      - main-proof-of-concept

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: ./scripts/build.sh
        run: docker push airtasker
        run: kubectl set-context ...
        run: ./scripts/deploy.sh